spring:
  application:
    name: distribution-center-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: adminpass
      roles: ADMIN

logging:
  level:
    org:
      springframework: INFO

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:h2:mem:qadb
    driver-class-name: org.h2.Driver
    username: qa_user
    password: qapass

server:
  port: 8082
